<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Description>Redis Store for operational data and for Caching of Duende Identity Server</Description>
    <Authors>Ali Bazzi and Stephen Adams</Authors>
    <Company>Ali Bazzi and StoveTech</Company>
    <AssemblyVersion>7.3.2.0</AssemblyVersion>
    <PackageReleaseNotes>Supports Duende Identity Server v7.3.2</PackageReleaseNotes>
    <Version>8.0.2.0</Version>
    <PackageProjectUrl>https://github.com/brnn8r/Duende.IdentityServer.Contrib.RedisStore</PackageProjectUrl>
    <PackageIconUrl>https://identityserver.github.io/Documentation/assets/images/icons/IDserver_icon128.jpg</PackageIconUrl>
    <PackageIcon>icon.jpg</PackageIcon>
    <PackageTags>Redis Store Duende.IdentityServer.7.3.2</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Ali Bazzi and StoveTech</Copyright>
    <FileVersion>8.0.2.0</FileVersion>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityServer" Version="8.0.2" />
    <PackageReference Include="Duende.IdentityServer.Storage" Version="8.0.2" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" PrivateAssets="All" />
  </ItemGroup>


  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\netcoreapp3.1\IdentityServer4.Contrib.RedisStore.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Release\netcoreapp3.1\IdentityServer4.Contrib.RedisStore.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Duende.IdentityServer.Contrib.RedisStore.nuspec" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="3.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Include="icon.jpg" Pack="true" PackagePath="\" />
    <None Include="..\README.md" Pack="true" PackagePath="">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
